update: all
search: True
schedule: "every week"
requirements:
  - requirements.txt:
      # update all dependencies and pin them
      update: all
      pin: True
  - requirements/dev.txt:
      # don't update dependencies
      update: False
Pin: True
Default Branch: dev
Branch pre-fix: pyup-reqsupdate/
close_prs: True
